apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: helloapp
  name: helloapp
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloapp
      version: v1
  strategy:
    #type: Recreate
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  template:
    metadata:
      labels:
        app: helloapp
        version: v1
    spec:
      containers:
      - image: mbevc1/helloapp:latest
        name: helloapp
        ports:
        - containerPort: 8080
